# Banking marketing campaign


## 📝**Project Introduction**

### Banking Marketing Campaign

**→ Business Insight**

>Long-term deposits allow banks to hold money for a specific period of time, allowing the bank to use that money to enhance its investments. Marketing campaigns for this product are based on phone calls. If a user is not available at a given time, then they will be called back at another time.

**→ Description of the problem**

>The Portuguese bank is experiencing a decline in revenue, so they want to be able to identify existing customers who are more likely to take out a long-term deposit. This will allow the bank to focus their marketing efforts on those customers and avoid wasting money and time on customers who are unlikely to sign up.  
To address this problem we will create a ranking algorithm to help predict whether or not a customer will sign up for a long-term deposit.

**→ Dictionary:** 
>In this dataset, you will find the following variables:
>1. `age`. Age of customer (numeric)
>2. `job`. Type of job (categorical)
>3. `marital`. Marital status (categorical)
>4. `education`. Level of education (categorical)
>5. `default`. Do you currently have credit (categorical)
>6. `housing`. Do you have a housing loan (categorical)
>7. `loan`. Do you have a personal loan? (categorical)
>8. `contact`. Type of contact communication (categorical)
>9. `month`. Last month in which you have been contacted (categorical)
>10. `day_of_week`. Last day on which you have been contacted (categorical)
>11. `duration`. Duration of previous contact in seconds (numeric)
>12. `campaign`. Number of contacts made during this campaign to the customer (numeric)
>13. `pdays`. Number of days that elapsed since the last campaign until the customer was contacted (numeric)
>14. `previous`. Number of contacts made during the previous campaign to the customer (numeric)
>15. `poutcome`. Result of the previous marketing campaign (categorical)
>16. `emp.var.rate`. Employment variation rate. Quarterly indicator (numeric)
>17. `cons.price.idx`. Consumer price index. Monthly indicator (numeric)
>18. `cons.conf.idx`. Consumer confidence index. Monthly indicator (numeric)
>19. `euribor3m`. EURIBOR 3-month rate. Daily indicator (numeric)
>20. `nr.employed`. Number of employees. Quarterly indicator (numeric)
>21. `y`. TARGET. Whether the customer takes out a long-term deposit or not (categorical)

---
---

## 🧩**Section 0: Loading Libraries, Modules, Funtions**

🟠**Step 1: Instalo las Librerias**

Desde la terminal, instalamos los paquetes / librerias que necesitaremos.  
Hay dos formas de hacerlo.  
>(1) Desde la terminal, usando el comando **pip install**  

        python -m pip install ipykernel nbformat pandas seaborn scikit-learn plotly

>(2) Usando el archivo **requirements.txt**  
>>Este archivo se puede generar una vez que las librerias ya fueron instaladas.  
>>El archivo contiene todas las librerias instaladas, incluyendo sus versiones.  
>>En este caso, el comando seria:

        python -m pip install -r requirements.txt

>"python -m":    
>>Llama al modulo pip, que es un instalador de paquetes  

>"intall":       
>>Luego del install le indicamos a ese modulo, que paquetes nos interesa que instale listandoselos, o de lo contrario, refiriendonos a un txt que incluye esa lista. 
>>Por convenvion se le llama "requirements.txt". 

**Es buena practica**, que siempre que generemos un entonrno virtual, tambien generemos un archivo "requirements.txt", para que al utilizarlo otra persona, se instalen exactamente las mismas librerias que utilizamos nosotros, a los efecectos de reproducibilidad.

En la terminal ------------------------------  

**Instalo** librerias de requirements file: 

        python -m pip install -r requirements.txt  

**Actualizo** archivo requirements.txt:  

        python -m pip freeze > requirements.txt

🟠**Step 2: Loading Libraries**  
De las librerias instaladas, cargo/importo las que necesito para mi proyecto, clasificandolas por ejemplo de esta manera:

>**Basic** Libraries ----------------------------------------  
>**Graphic** Libraries ----------------------------------------   
>**Machine** Learning Libraries -------------------------------

In [195]:
# Basic Libraries ---------------------------------------- 
import pandas as pd
import numpy as np

# Machine Learning ----------------------------------------
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import chi2, SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import folium 
from folium.plugins import MarkerCluster

🟠**Step 3: Import/Define the Needed Modules and Funtions**
>Los modulos son scripts de python que generalmente tienen algunas funciones definidas para agilitar el proceso.

>  Defined Funtion:  💡**count_nan_zeros_uniques**💡  
>> Para cada columna de mi df, se encargue de contar:  
>> los nan (not a number)  
>> los zeros  
>> los valores unicos

In [196]:
''' 
En este caso definiremos la funcion:
📌📌📌 count_nan_zeros_uniques 📌📌📌
que se encargue de contar los nan (not a number), los zeros y los valores unicos para cada columna de mi df.
'''
def count_nan_zeros_uniques(df): # El argumento que le pasamos a la funcion es un dataframe
    nan_zeros_uniques = {}       # Generamos un diccionario vacio
    for col in df.columns: # Generamos un loop que mire cada columna del dataframe y
        total_count = len(df[col]) # Cuente el nro de observaciones (filas) 
        nan_count = df[col].isna().sum()  # Cuente el nro de nan en cada columna 
        zero_count = (df[col]==0).sum()  # Cuente el nro de zeros en cada columna 
        unique_count = df[col].nunique()  # Cuente el nro de valores unicos que hay en cada columna 
        nan_zeros_uniques[col] = { # Guardo los valores obtenidos, en las siguientes claves del diccionario
            "NaNs" : nan_count,
            "Zeros" : zero_count,
            "Uniques" : unique_count
        }
    return pd.DataFrame.from_dict(nan_zeros_uniques, orient = "index") 
# Convierto ese diccionario en un dataframe. 
# Orient ="Index" indica la forma en la que quiero que despliegue la info.
# .T transpone la data, si eso nos quedara mas comodo.

---
---

## 🧩**Section 1: Loading the dataset**
> Defino la url  
> Cargo el data frame en df_raw

>The dataset can be found in this project folder under the name `bank-marketing-campaign-data.csv`, and you can load it into the code directly from this link:
>```text
>https://raw.githubusercontent.com/4GeeksAcademy/logistic-regression-project-tutorial/main/bank-marketing-campaign-data.csv
>```
>Or download it, and add it by hand in your repository.

In [197]:
url = ("https://raw.githubusercontent.com/4GeeksAcademy/logistic-regression-project-tutorial/main/bank-marketing-campaign-data.csv")
df_raw = pd.read_csv(url, sep = ";")

# Este archivo CSV contiene puntos y comas en lugar de comas como separadores

---
---


## 🧩**Section 2: EDA**

>Code to process the data before modeling.  
>This step is vital to ensure that we keep the variables that are strictly necessary and eliminate those that are not relevant or do not provide information.  
>Conveniently divide the data set into `train` and `test` as we have seen in previous lessons.


🟠**Step 1: Tomo una muestra aleatoria de datos (10 Registros)**
> .sample(10, random_state=2025)
> Ponemos un valor cualquiera en random_state para que si corremos otra vez el codigo, nos traiga la misma muestra, y asi toda la clase trabaja con los mismos valores. O todo el proyecto trabajo con los mismos ejemplos.

In [198]:
df_raw.sample(10,random_state=2025)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
4479,58,retired,married,basic.4y,unknown,no,no,telephone,may,tue,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,yes
24230,51,entrepreneur,married,university.degree,no,yes,no,cellular,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no
8307,43,admin.,married,high.school,no,yes,no,telephone,jun,tue,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.864,5228.1,no
4824,31,admin.,married,high.school,no,no,no,telephone,may,wed,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.858,5191.0,no
12201,41,blue-collar,married,basic.6y,no,no,no,telephone,jul,wed,...,5,999,0,nonexistent,1.4,93.918,-42.7,4.956,5228.1,no
20123,36,housemaid,married,basic.6y,no,no,no,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
11995,44,admin.,married,university.degree,unknown,yes,yes,telephone,jun,thu,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.955,5228.1,no
9514,45,admin.,married,university.degree,no,yes,no,telephone,jun,mon,...,5,999,0,nonexistent,1.4,94.465,-41.8,4.961,5228.1,no
20217,48,entrepreneur,married,university.degree,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
8739,22,services,single,high.school,no,no,no,telephone,jun,wed,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.864,5228.1,no


🟠**Step 2: Estudio la composicion del dataset**  
> .info():  
> vemos por arriba como esta compuesto nuestro dataset.   
> Columnas (Observaciones), Tipo de Datos, Cantidad de nullos, etc

In [199]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

🟠**Step 4: Identificando, nan, zeros, y valores unicos de cada columna**  
>count_nan_zeros_uniques(df)  
>Para esto usamos la funcion que definimos mas arriba count_nan_zeros_uniques

In [200]:
count_nan_zeros_uniques(df_raw)

                NaNs  Zeros  Uniques
age                0      0       78
job                0      0       12
marital            0      0        4
education          0      0        8
default            0      0        3
housing            0      0        3
loan               0      0        3
contact            0      0        2
month              0      0       10
day_of_week        0      0        5
duration           0      4     1544
campaign           0      0       42
pdays              0     15       27
previous           0  35563        8
poutcome           0      0        3
emp.var.rate       0      0       10
cons.price.idx     0      0       26
cons.conf.idx      0      0       26
euribor3m          0      0      316
nr.employed        0      0       11
y                  0      0        2

🟠Step 6: **Identificar vectores con valores unicos**, (si no tuviera creada la funcion count_nan_zeros_uniques(df)):
* 1er forma:
  df_baking['name'].value_counts()  
  Muestra una lista de todos los nombres unicos, con el conteo de sus repeticiones al lado.
* 2da Forma:
  df_baking["name"].nunique()  
  Me devuelve la cantidad de valores unicos que hay, excluyendo los nan por defecto.

🟠Step 7: **Identifying Actions Needed**
1. Identificar **tipo de datos** a corregir y/o optimizar.
    * **Categorizamos** las variables Necesarias: df_baking["field"] = df_baking["field"].astype('cagtegory) 
    * Cuando los datos son clasificaciones, y el dataset las expresa como numeros, primero debemos convertirlos a texto, por ejemplo usando un **replace**. De lo contrario no nos dejara cambiar el tipo a categorical. 
    Ejemplo: dfdf['class'] = dfdf['pclass'].replace({1 : 'A', 2 : 'B', 3 : 'C'}) 
2. Identificamos columnas con **Valores Unicos**, para eliminarlas, ya que no nos estaria aportando info desde el punto de vista estadistico. No tienen poder interpretativo. En general son Id Fields
3. Identificar columnas que solo incluyen **nans**

>Recordar que Cada columna es un vector de datos

In [201]:
# Esto nos sirve para tomar desiciones. 
# Ejemplo:

#🟡 COLUMNAS CON UN SOLO VALOR UNICO: 
    # los datos con un solo valor unico no tienen variabilidad, 
    # la ausencia de variabilidad me quita especificacion, me quita explicacion 
    # Implica ausencia de Analisis, de Explicabilidad, AUSENCIA DE PREDICTIBILIDAD. 
    # por lo tanto esas columnas las quito.
    # Si tengo un grupo de peruanos, donde todos son peruanos. Que tengo para explicar? 
    # Nada, mas que todos son peruanos.

    # No hay columnas con esta caracteristica.

#🟡 COLUMNAS QUE SOLO CONTIENEN nans: 
    # Columnas que tienen = cantidad de Nans y Filas.
    # No aportan informacion, asi que las sacamos.

    # No hay columnas con esta caracteristica.


#🟡 COLUMNAS CON = cantidad de Uniques que Raws: 
    # Columnas que tienen = cantidad de Uniques y Filas.
    # Generalmente son los Id Fields.
    # No aportan informacion, asi que las sacamos.

    # No hay columnas con esta caracteristica.

#🟡 ACCIONES A TOMAR:
    # De acuerdo a lo visto mas arriba, no habrian acciones a tomar.

🟠Step 8: **Data preprocessing**
>Perform the data cleaning, data transformation and data reduction steps to avoid data mistmatching, noisy data or data not wrangled

💡**Generamos el dataframe df_baking, para comenzar a limpiar el dataframe**  
>NUNCA HAcemos Transformaciones con df_raw, asi mantenemos la data original.  
>df_baking = df_raw.copy() # Copio el rawdata y lo guardo en df_baking

>Lo que hacemos es crear una copia, para trabajar sobre ella y no modificar la base original.
>A ella se le llama df_backing, dando a entender que esta en proceso.

In [202]:
df_baking = df_raw.copy() # Copio el rawdata y lo guardo en df_baking

💡**Eliminamos columnas por su posicion**
* Ejemplo: La primer y ultimas dos columnas no sirven por ser ID Fields
* Las eliminamos de esta forma:  
  df_baking = df_baking.iloc[:,1:-2]  
  → iloc selecciona informacion en base al nro de la fila y la columna.  
    Al dejar el primer parametro vacio, le estoy diciendo que quiero todas las filas.  
  → Con "1:-2" Como se le este slicing:  No voy a tomar ni la primer columna (la columna 0), ni la penultima, ni la ultima.

💡**Eliminamos los vectores/columnas/variables que no nos aportan en el EDA: con .drop([])**
* Ya sea por motivos conceptuales o estadisticos, extraemos las variables qeu no sirven, con  
  .drop(['Vector'], axis=1) colocando axis =1 para indicar que son columnas.  
  El 1 es columnas, y el 0 es filas.  
* Ejemplo:   
  df_baking = df_baking.drop(['Vector1','Vector2','Vector3'], axis=1)
* No es buena practica tener que scrollear para leer una linea, asi que lo hacemos en partes.

💡**Modificaremos el tipo de datos:**  
* Por ejemplo:  
Para longitud o latitud, la separacion decimal llego como "," y debe ser "." para que reconozca esos valores como decimales y no como object
* df_baking['latitude'] = df_baking['latitude'].apply(lambda x: float( x.replace("," , ".")))
* df_baking['longitude'] = df_baking['longitude'].apply(lambda x: float( x.replace("," , ".")))

💡 **Generacion de Nuevas Variables**
>Es en esta etapa, no solamente es el momento de eliminar variables que no nos sirven, si no tambien crear variables nuevas, apoyadas en variables que son debiles para explicar algo, o que directamente no explican nada por si solas.

>Hagamos el ejemplo con el vector cabinas, que nos dice el nro de cabina.  
>df_baking['cabin'].nunique()  
>Vemos que 186 de 295 valores no nulos, son unicos. 
>Dado de que son cabinas distintas, en vez de preocuparnos si el nro de cabina es B5 o C85, podriamos crear 
>una variable nueva, que a partir de esta diga:  
>* Si has viajado en cabina: Yes, 
>* Si no has viajado en cabina: No. Los nan son los que no viajaron en cabina.

> Creamos la variable binaria o categorica, que informa si viajas en cabina o no:  
>* df_baking['travel_cabin'] = ['no' if pd.isna(x) else 'yes' for x in df_baking['cabin']]  
>* df_baking["travel_cabin"].value_counts()  

>Como cabin se a transformado a travel_cabin, eliminamos el vector cabin indicando si queremos sacar filas o columnas. El 1 es columnas, y el 0 es filas. 
>* df_baking = df_baking.drop(['cabin'], axis=1)

💡**Copiamos df_baking:**

>Luego de que terminamos de preparar nuestra base, NO OLVIDAR, hacer una copia de la misma, para que no se rompa nada con los siguientes pasos.  
>df = df_baking.copy()

In [203]:
df = df_baking.copy()

💡**Ultimo Check antes de dejar el df definitivo**  
>Hacemos un .info() y un .sample() para ver como nos quedo la base hasta ahora

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [205]:
df.sample(10, random_state=2025)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
4479,58,retired,married,basic.4y,unknown,no,no,telephone,may,tue,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,yes
24230,51,entrepreneur,married,university.degree,no,yes,no,cellular,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no
8307,43,admin.,married,high.school,no,yes,no,telephone,jun,tue,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.864,5228.1,no
4824,31,admin.,married,high.school,no,no,no,telephone,may,wed,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.858,5191.0,no
12201,41,blue-collar,married,basic.6y,no,no,no,telephone,jul,wed,...,5,999,0,nonexistent,1.4,93.918,-42.7,4.956,5228.1,no
20123,36,housemaid,married,basic.6y,no,no,no,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
11995,44,admin.,married,university.degree,unknown,yes,yes,telephone,jun,thu,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.955,5228.1,no
9514,45,admin.,married,university.degree,no,yes,no,telephone,jun,mon,...,5,999,0,nonexistent,1.4,94.465,-41.8,4.961,5228.1,no
20217,48,entrepreneur,married,university.degree,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.965,5228.1,no
8739,22,services,single,high.school,no,no,no,telephone,jun,wed,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.864,5228.1,no


🟠Step 9: **Normalizacion de Datos**:

* **¿Qué es la Normalización?**
* La normalización es una técnica para escalar los valores de una variable a un rango específico, normalmente entre 0 y 1. Se usa cuando los datos tienen rangos muy distintos y queremos hacerlos comparables.

* Por ejemplo, si tienes precios de casas que van desde 50,000 hasta 2,000,000, el rango es muy grande. Si en otro análisis tienes una variable como "número de habitaciones" (que va de 1 a 10), las escalas son muy diferentes.
Sin normalizar, el precio dominaría cualquier análisis, ya que sus valores son mucho mayores que los de las habitaciones.

* La fórmula de Min-Max Normalization es:  
    **X_normalizado = (X - X_min) / (X - X_max)**  
    X es el valor original de la variable.  
    X_min es el valor mínimo de la variable.  
    X_max es el valor máximo de la variable.  
    X_normalizado es el valor transformado, que siempre estará entre 0 y 1.  

* **¿Por qué los valores quedan entre 0 y 1?**
* Imagina que en una ciudad el precio más barato de una casa es 50,000 y el más caro es 2,000,000.
* Si queremos normalizar un precio de 500,000, hacemos:
    El precio más bajo (50,000) se convierte en 0.
    El precio más alto (2,000,000) se convierte en 1.
    Todos los demás valores se distribuyen entre 0 y 1 según su posición relativa.

* **¿Cuándo es útil normalizar?**
* Para comparar variables con diferentes escalas  
  Si una variable tiene valores muy grandes (como precios de casas) y otra valores pequeños (como número de habitaciones), normalizar permite analizarlas juntas.

* Para algoritmos de Machine Learning  
  Algunos modelos (como regresión logística, redes neuronales, KNN, etc.) funcionan mejor cuando los datos están normalizados. Evita que una variable con valores grandes domine el modelo.

* Para visualizar mejor los datos  
  Si graficamos varias poblaciones con precios muy diferentes, normalizar permite comparar la distribución de precios sin que una población con precios muy altos opaque a las demás.

* **Resumen rápido:**  
* La normalización transforma los valores de una variable a un rango entre 0 y 1.
* Se usa cuando las escalas de los datos son muy diferentes.
* Permite comparar variables en igualdad de condiciones.
* Es clave para algunos algoritmos de Machine Learning y para hacer gráficos más claros.

* **Metodos para Normalizar:**  
>Hay distintas formas de normalizar mis variables. Por ejemplo:  
* Definiendo una función para normalizar precios usando Min-Max Scaling, (Se usa la técnica de Min-Max Scaling, que convierte los valores entre 0 y 1.)  
    def min_max_normalize(df):  
       min_price = df['price'].min()  # Obtener el precio mínimo en la población  
       max_price = df['price'].max()  # Obtener el precio máximo en la población  
       df['norm'] = (df['price'] - min_price) / (max_price - min_price)  # Normalizar la columna 'price'  
       return df  

    Luego aplicamos la normalización a cada población:  
       df_cs.groupby('level5').apply(min_max_normalize)

In [206]:
# ==============================================================
# PREPROCESAMIENTO DE DATOS: FACTORIZACIÓN Y NORMALIZACIÓN
# ==============================================================

# ==============================================================
# 1. CONVERSIÓN DE VARIABLES CATEGÓRICAS A VALORES NUMÉRICOS
# ==============================================================

# Dado que los modelos de Machine Learning requieren datos numéricos,
# convertimos las variables categóricas en números enteros usando pd.factorize()

df["job_n"] = pd.factorize(df["job"])[0]
df["marital_n"] = pd.factorize(df["marital"])[0]
df["education_n"] = pd.factorize(df["education"])[0]
df["default_n"] = pd.factorize(df["default"])[0]
df["housing_n"] = pd.factorize(df["housing"])[0]
df["loan_n"] = pd.factorize(df["loan"])[0]
df["contact_n"] = pd.factorize(df["contact"])[0]
df["month_n"] = pd.factorize(df["month"])[0]
df["day_of_week_n"] = pd.factorize(df["day_of_week"])[0]
df["poutcome_n"] = pd.factorize(df["poutcome"])[0]
df["y_n"] = pd.factorize(df["y"])[0]

# ¿Cómo funciona pd.factorize()?
# - Convierte cada categoría en un número entero.
# - Ejemplo:
#   pd.factorize(["single", "married", "divorced", "married", "single"])
#   Resultado: (array([0, 1, 2, 1, 0]), Index(['single', 'married', 'divorced'], dtype='object'))
#   Donde: "single" -> 0, "married" -> 1, "divorced" -> 2

# ==============================================================
# 2. NORMALIZACIÓN DE VARIABLES NUMÉRICAS CON MinMaxScaler
# ==============================================================

# Definimos las columnas numéricas que vamos a normalizar
num_variables = [
    "job_n", "marital_n", "education_n", "default_n", "housing_n", "loan_n", 
    "contact_n", "month_n", "day_of_week_n", "poutcome_n",
    "age", "duration", "campaign", "pdays", "previous", 
    "emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed", "y_n"
]

# Inicializamos el MinMaxScaler
scaler = MinMaxScaler()

# Aplicamos el escalador para transformar los datos en el rango [0, 1]
scaled_features = scaler.fit_transform(df[num_variables])

# Convertimos los datos escalados en un nuevo DataFrame con los mismos nombres de columnas
df_scaled = pd.DataFrame(scaled_features, index=df.index, columns=num_variables)

# ==============================================================
# ¿Cómo funciona MinMaxScaler?
# ==============================================================
# - Transforma los valores de cada columna para que estén en un rango de 0 a 1.
# - Se usa la fórmula:
#   X_scaled = (X - X_min) / (X_max - X_min)
# - Esto evita que algunas características dominen sobre otras debido a diferencias de magnitud.
# - También ayuda a mejorar la convergencia en algoritmos de Machine Learning.

# ==============================================================
# RESUMEN DEL PROCESO
# ==============================================================
# ✅ Factorizamos variables categóricas en valores numéricos.
# ✅ Normalizamos todas las variables en un rango de [0, 1].
# ✅ Preparamos los datos para modelos de Machine Learning.
# ==============================================================

# Ahora los datos están listos para ser usados en modelos predictivos

# Mostramos los primeros registros del nuevo DataFrame escalado
df_scaled.head()

,job_n,marital_n,education_n,default_n,housing_n,loan_n,contact_n,month_n,day_of_week_n,poutcome_n,...,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y_n
0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.053070,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
1,0.090909,0.0,0.142857,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.030297,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
2,0.090909,0.0,0.142857,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.045954,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
3,0.181818,0.0,0.285714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.030704,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0
4,0.090909,0.0,0.142857,0.0,0.0,0.5,0.0,0.0,0.0,0.0,...,0.062424,0.0,1.0,0.0,0.9375,0.698753,0.60251,0.957379,0.859735,0.0

In [207]:
# ==============================================================
# SELECCIÓN DE CARACTERÍSTICAS (FEATURE SELECTION) USANDO CHI-CUADRADO
# ==============================================================


# ==============================================================
# 🔹 1. SEPARACIÓN DE VARIABLES INDEPENDIENTES Y DEPENDIENTE
# ==============================================================

# Definimos las variables:
# - X: Contiene las variables predictoras (independientes).
# - y: Contiene la variable objetivo (dependiente) que queremos predecir.

X = df_scaled.drop("y_n", axis=1)  # Eliminamos "y_n" para obtener solo las características
y = df_scaled["y_n"]  # Almacenamos la variable objetivo

# Ahora:
# - `X` contiene todas las variables predictoras.
# - `y` almacena el valor que queremos predecir.

# ==============================================================
# 🔹 2. DIVISIÓN DEL CONJUNTO DE DATOS EN ENTRENAMIENTO Y PRUEBA
# ==============================================================

# Dividimos el dataset en:
# - 90% datos de entrenamiento
# - 10% datos de prueba

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, random_state=42  
)

# ¿Qué hace `train_test_split()`?
# - `test_size=0.1`: Reserva el 10% de los datos para pruebas.
# - `random_state=42`: Asegura que la división sea siempre la misma en cada ejecución. 
#                      Fijamos random_state para obtener resultados reproducibles

# ==============================================================
# 🔹 3. SELECCIÓN DE LAS MEJORES CARACTERÍSTICAS CON CHI-CUADRADO
# ==============================================================

# Aplicamos la selección de características usando `SelectKBest` con `chi2`
# - La función `chi2` mide la relación entre cada variable independiente y la variable objetivo.
# - Se seleccionan las 5 características más relevantes.

selection_model = SelectKBest(chi2, k=5)  # Seleccionamos las 5 características más importantes
selection_model.fit(X_train, y_train)  # Ajustamos el modelo en los datos de entrenamiento

# Obtenemos un array booleano con las características seleccionadas
# - `True` indica que la característica fue seleccionada.
# - `False` indica que la característica no fue seleccionada.

ix = selection_model.get_support()

# ==============================================================
# 🔹 4. TRANSFORMACIÓN DE LOS CONJUNTOS DE DATOS
# ==============================================================

# Transformamos los conjuntos de entrenamiento y prueba para conservar solo las características seleccionadas
X_train_sel = pd.DataFrame(
    selection_model.transform(X_train),  # Transformamos los datos
    columns=X_train.columns.values[ix]  # Mantenemos los nombres de las columnas seleccionadas
)

X_test_sel = pd.DataFrame(
    selection_model.transform(X_test),
    columns=X_test.columns.values[ix]
)

# Ahora `X_train_sel` y `X_test_sel` contienen solo las 5 características más relevantes.

# ==============================================================
# 🔹 5. RESULTADOS Y EXPLICACIÓN DEL MÉTODO
# ==============================================================

# ¿Cómo funciona SelectKBest(chi2)?
# - `chi2` mide la dependencia entre cada característica y la variable objetivo.
# - Cuanto mayor sea el valor de chi-cuadrado, más relevante es la característica.
# - Es útil en datos categóricos y datos numéricos discretizados.
# - Aquí hemos seleccionado las 5 características con los valores más altos de chi-cuadrado.


# ==============================================================
# ✅ RESUMEN DEL PROCESO
# ==============================================================
# 1️⃣ Separamos las variables independientes (X) y la variable objetivo (y).
# 2️⃣ Dividimos los datos en entrenamiento (90%) y prueba (10%).
# 3️⃣ Aplicamos SelectKBest con chi2 para seleccionar las 5 mejores características.
# 4️⃣ Transformamos X_train y X_test para conservar solo las mejores características.
# ==============================================================

# Ahora `X_train_sel` y `X_test_sel` están listos para ser utilizados en un modelo de Machine Learning.

In [208]:
# Mostramos las primeras filas del nuevo conjunto de entrenamiento con las características seleccionadas
X_train_sel.head()

   poutcome_n  previous  emp.var.rate  euribor3m  nr.employed
0         0.0       0.0      0.000000   0.019497     0.203781
1         0.0       0.0      1.000000   0.981183     1.000000
2         0.0       0.0      0.333333   0.138291     0.512287
3         0.0       0.0      0.937500   0.956926     0.859735
4         0.0       0.0      0.937500   0.957379     0.859735

In [209]:
# Mostramos las primeras filas del nuevo conjunto de prueba con las características seleccionadas
X_test_sel.head()

   poutcome_n  previous  emp.var.rate  euribor3m  nr.employed
0         0.5  0.142857      0.333333   0.150759     0.512287
1         0.0  0.000000      0.937500   0.958059     0.859735
2         0.5  0.142857      0.333333   0.153933     0.512287
3         0.0  0.000000      1.000000   0.982317     1.000000
4         0.0  0.000000      1.000000   0.981410     1.000000

In [210]:
# ==============================================================
# 🔹 EXPORTACIÓN DE LOS CONJUNTOS DE DATOS LIMPIOS
# ==============================================================

# Añadimos la variable objetivo "y_n" de vuelta a los conjuntos de entrenamiento y prueba
# - "y_n" es la columna que queremos predecir, así que la reincorporamos después de la selección de características.

X_train_sel["y_n"] = list(y_train)  # Agregamos la variable objetivo al conjunto de entrenamiento
X_test_sel["y_n"] = list(y_test)    # Agregamos la variable objetivo al conjunto de prueba

# ==============================================================
# 🔹 GUARDADO DE LOS ARCHIVOS LIMPIOS EN CSV
# ==============================================================

# Guardamos los conjuntos de datos preprocesados en archivos CSV
# - Esto nos permitirá cargarlos directamente sin necesidad de repetir el preprocesamiento.

X_train_sel.to_csv("clean_train.csv", index=False)  # Guardamos el conjunto de entrenamiento
X_test_sel.to_csv("clean_test.csv", index=False)    # Guardamos el conjunto de prueba

# Ahora tenemos los datasets listos para ser utilizados en modelos de Machine Learning.
# - `clean_train.csv`: Contiene las características seleccionadas + variable objetivo para entrenamiento.
# - `clean_test.csv`: Contiene las características seleccionadas + variable objetivo para prueba.

# 🚀 Los datos preprocesados están listos para ser usados en la siguiente fase del proyecto.

---
---

## 🧩**Section 3: Build a logistic regression model**
You do not need to optimize the hyperparameters. Start by using a default definition and improve it in the next step.

In [211]:
# ==============================================================
# 🔹 CARGA DE LOS CONJUNTOS DE DATOS LIMPIOS
# ==============================================================

# Cargamos los archivos CSV previamente guardados
# - `clean_train.csv`: Contiene las características seleccionadas y la variable objetivo para entrenamiento.
# - `clean_test.csv`: Contiene las características seleccionadas y la variable objetivo para prueba.


train_data = pd.read_csv("clean_train.csv") # Cargamos los datos de entrenamiento
test_data = pd.read_csv("clean_test.csv")   # Cargamos los datos de prueba

In [212]:
train_data.head() #VERIFICACIÓN DE LA CARGA DE DATOS

   poutcome_n  previous  emp.var.rate  euribor3m  nr.employed  y_n
0         0.0       0.0      0.000000   0.019497     0.203781  1.0
1         0.0       0.0      1.000000   0.981183     1.000000  0.0
2         0.0       0.0      0.333333   0.138291     0.512287  0.0
3         0.0       0.0      0.937500   0.956926     0.859735  0.0
4         0.0       0.0      0.937500   0.957379     0.859735  0.0

In [213]:
test_data.head() #VERIFICACIÓN DE LA CARGA DE DATOS

   poutcome_n  previous  emp.var.rate  euribor3m  nr.employed  y_n
0         0.5  0.142857      0.333333   0.150759     0.512287  0.0
1         0.0  0.000000      0.937500   0.958059     0.859735  0.0
2         0.5  0.142857      0.333333   0.153933     0.512287  0.0
3         0.0  0.000000      1.000000   0.982317     1.000000  0.0
4         0.0  0.000000      1.000000   0.981410     1.000000  0.0

In [214]:
# ==============================================================
# 🔹 SEPARACIÓN DE VARIABLES INDEPENDIENTES Y DEPENDIENTE
# ==============================================================

# Extraemos las variables predictoras (X) y la variable objetivo (y)
# - X: Contiene las características seleccionadas (sin la variable objetivo).
# - y: Contiene la variable objetivo "y_n", que representa la clase a predecir.

# Separación en el conjunto de entrenamiento
X_train = train_data.drop(["y_n"], axis=1)  # Eliminamos "y_n" para obtener solo las características
y_train = train_data["y_n"]  # Almacenamos la variable objetivo

# Separación en el conjunto de prueba
X_test = test_data.drop(["y_n"], axis=1)  # Eliminamos "y_n" para obtener solo las características
y_test = test_data["y_n"]  # Almacenamos la variable objetivo

In [215]:
# ==============================================================
# 🔹 ENTRENAMIENTO DEL MODELO DE REGRESIÓN LOGÍSTICA
# ==============================================================


# ==============================================================
# 🔹 INICIALIZACIÓN Y ENTRENAMIENTO DEL MODELO
# ==============================================================

# Creamos una instancia del modelo de Regresión Logística
# - Este modelo es ampliamente utilizado para problemas de clasificación binaria.
# - Aprende una función matemática que modela la probabilidad de pertenecer a una clase.

model = LogisticRegression()  # Creamos el modelo

# Entrenamos el modelo con los datos de entrenamiento
# - `X_train` contiene las características seleccionadas.
# - `y_train` contiene las etiquetas correspondientes.
model.fit(X_train, y_train)

# Ahora el modelo ha aprendido una relación entre las características y la variable objetivo.
# - Se ha ajustado a los patrones presentes en `X_train`.
# - Está listo para realizar predicciones en datos nuevos.

# A continuación, podemos evaluar su rendimiento sobre el conjunto de prueba.

LogisticRegression()

In [216]:
# ==============================================================
# 🔹 PREDICCIÓN CON EL MODELO ENTRENADO
# ==============================================================

# Usamos el modelo entrenado para hacer predicciones sobre el conjunto de prueba.
# - `model.predict(X_test)`: Toma las características de prueba y genera predicciones.

y_pred = model.predict(X_test)  # Generamos las predicciones

# ==============================================================
# 🔹 VISUALIZACIÓN DE LAS PREDICCIONES
# ==============================================================

# Mostramos las primeras 10 predicciones generadas por el modelo
print("Primeras 10 predicciones del modelo:")
print(y_pred[:10])

# Ahora tenemos las predicciones (`y_pred`) correspondientes a los valores en `X_test`.
# - `y_pred` es un array con valores predichos (0 o 1 en el caso de clasificación binaria).
# - Podemos compararlo con `y_test` para evaluar el rendimiento del modelo.

# A continuación, procederemos a evaluar la precisión del modelo.

Primeras 10 predicciones del modelo:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [ ]:
accuracy_score(y_test, y_pred)

0.8953629521728574

---
---

## 🧩**Section 4:  Optimize the previous model**
After training the model, if the results are not satisfactory, optimize it using one of the techniques seen.

In [219]:
# ==============================================================
# 🔹 OPTIMIZACIÓN DE HIPERPARÁMETROS CON GRID SEARCH
# ==============================================================

# Importamos `GridSearchCV` de `sklearn.model_selection`
# - `GridSearchCV` busca automáticamente la mejor combinación de hiperparámetros 
#   probando distintas configuraciones en el modelo.

from sklearn.model_selection import GridSearchCV

# ==============================================================
# 🔹 DEFINICIÓN DEL ESPACIO DE BÚSQUEDA DE HIPERPARÁMETROS
# ==============================================================

# Definimos los hiperparámetros a probar en la búsqueda
# - `C`: Coeficiente de regularización (valores pequeños aplican más regularización).
# - `penalty`: Tipo de regularización (L1, L2, ElasticNet o sin regularización).
# - `solver`: Algoritmo de optimización para la regresión logística.

hyperparams = {
    "C": [0.001, 0.01, 0.1, 1, 10, 100, 1000],  # Valores de la regularización
    "penalty": ["l1", "l2", "elasticnet", None],  # Tipos de penalización
    "solver": ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]  # Métodos de optimización
}

# ==============================================================
# 🔹 CONFIGURACIÓN DE GRID SEARCH
# ==============================================================

# Inicializamos `GridSearchCV` para encontrar la mejor combinación de hiperparámetros
# - `model`: Modelo de Regresión Logística previamente entrenado.
# - `hyperparams`: Diccionario con las opciones de hiperparámetros a probar.
# - `scoring="accuracy"`: Optimiza la búsqueda para maximizar la precisión.
# - `cv=10`: Realiza validación cruzada con 10 particiones para evaluar cada configuración.

grid = GridSearchCV(model, hyperparams, scoring="accuracy", cv=10)

# Ahora `grid` está listo para ejecutar la búsqueda de hiperparámetros.
# - La búsqueda aún no se ha ejecutado, solo hemos definido la configuración.
# - Para ejecutar la búsqueda, debemos usar `grid.fit(X_train, y_train)`.

# A continuación, procederemos a entrenar `GridSearchCV` para encontrar la mejor configuración.

grid

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
                         'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [220]:
# ==============================================================
# 🔹 ENTRENAMIENTO DE GRID SEARCH Y BÚSQUEDA DE MEJORES HIPERPARÁMETROS
# ==============================================================

# Supresión de advertencias innecesarias
# - Algunas combinaciones de hiperparámetros pueden generar advertencias en scikit-learn.
# - Definimos una función `warn` vacía para ignorar estos mensajes.

def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn  # Sobrescribimos la función de advertencias

# ==============================================================
# 🔹 EJECUCIÓN DE GRID SEARCH
# ==============================================================

# Entrenamos `GridSearchCV` con los datos de entrenamiento.
# - Esto probará todas las combinaciones de hiperparámetros en `hyperparams`.
# - Usará validación cruzada (`cv=10`) para evaluar cada configuración.

grid.fit(X_train, y_train)

# ==============================================================
# 🔹 RESULTADOS: MEJOR COMBINACIÓN DE HIPERPARÁMETROS
# ==============================================================

# Mostramos la mejor combinación de hiperparámetros encontrada por `GridSearchCV`
print(f"✅ Mejores hiperparámetros encontrados: {grid.best_params_}")

# Ahora tenemos los valores óptimos de los hiperparámetros para nuestro modelo.
# - Podemos usar estos valores para volver a entrenar el modelo con la mejor configuración.

# A continuación, podemos evaluar el rendimiento del modelo optimizado.

✅ Mejores hiperparámetros encontrados: {'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}

In [221]:
# ==============================================================
# 🔹 ENTRENAMIENTO DEL MODELO CON LOS MEJORES HIPERPARÁMETROS
# ==============================================================

# Creamos una nueva instancia de `LogisticRegression` con los hiperparámetros óptimos.
# - `C=0.1`: Coeficiente de regularización que equilibra ajuste vs. complejidad del modelo.
# - `penalty="l2"`: Aplica regularización L2 (Ridge), que previene sobreajuste.
# - `solver="liblinear"`: Método de optimización eficiente para regresión logística con L1/L2.

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(C=0.1, penalty="l2", solver="liblinear")  # Definimos el modelo optimizado

# ==============================================================
# 🔹 ENTRENAMIENTO DEL MODELO OPTIMIZADO
# ==============================================================

# Ajustamos el modelo con los datos de entrenamiento.
# - `X_train` contiene las características seleccionadas.
# - `y_train` contiene la variable objetivo.

model.fit(X_train, y_train)

# Ahora el modelo ha sido entrenado con la mejor configuración encontrada en `GridSearchCV`.
# - Este modelo optimizado debería tener mejor rendimiento que el modelo inicial.

# A continuación, podemos evaluar el modelo con el conjunto de prueba.

LogisticRegression(C=0.1, solver='liblinear')

In [222]:
# ==============================================================
# 🔹 PREDICCIÓN CON EL MODELO OPTIMIZADO
# ==============================================================

# Utilizamos el modelo entrenado para hacer predicciones sobre el conjunto de prueba.
# - `model.predict(X_test)`: Toma las características de prueba y genera predicciones.

y_pred = model.predict(X_test)  # Generamos las predicciones

# ==============================================================
# 🔹 VISUALIZACIÓN DE LAS PREDICCIONES
# ==============================================================

# Mostramos las primeras 10 predicciones generadas por el modelo
print("📌 Primeras 10 predicciones del modelo optimizado:")
print(y_pred[:10])

# Ahora tenemos las predicciones (`y_pred`) correspondientes a los valores en `X_test`.
# - `y_pred` es un array con valores predichos (0 o 1 en el caso de clasificación binaria).
# - Podemos compararlo con `y_test` para evaluar el rendimiento del modelo.

# 🚀 A continuación, procederemos a evaluar la precisión del modelo optimizado.

📌 Primeras 10 predicciones del modelo optimizado:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [223]:
# ==============================================================
# 🔹 EVALUACIÓN DEL MODELO OPTIMIZADO: PRECISIÓN (ACCURACY)
# ==============================================================

# Importamos `accuracy_score` de `sklearn.metrics`
# - `accuracy_score` mide la proporción de predicciones correctas sobre el total de muestras.

from sklearn.metrics import accuracy_score

# ==============================================================
# 🔹 CÁLCULO DE LA PRECISIÓN DEL MODELO OPTIMIZADO
# ==============================================================

# Calculamos la precisión del modelo comparando `y_pred` (predicciones) con `y_test` (valores reales).
accuracy = accuracy_score(y_test, y_pred)

# Mostramos la precisión obtenida
print(f"✅ Precisión del modelo optimizado: {accuracy:.4f}")

# ==============================================================
# 🔹 INTERPRETACIÓN DEL RESULTADO
# ==============================================================
# - La precisión indica qué porcentaje de las predicciones fueron correctas.
# - Un valor cercano a 1.0 sugiere que el modelo está clasificando correctamente la mayoría de los casos.
# - Un valor bajo (< 0.5) indica que el modelo tiene dificultades para predecir correctamente.
# - Es importante complementar la precisión con otras métricas (ej. matriz de confusión, F1-score).

# A continuación, podemos calcular métricas adicionales para una evaluación más completa.

✅ Precisión del modelo optimizado: 0.8975

In [225]:
# ==============================================================
# 🔹 GUARDADO DEL MODELO ENTRENADO CON PICKLE
# ==============================================================

# Importamos `dump` de la librería `pickle`
# - `pickle` nos permite serializar y guardar objetos de Python en archivos binarios.

from pickle import dump

# ==============================================================
# 🔹 ALMACENAMIENTO DEL MODELO OPTIMIZADO
# ==============================================================

# Guardamos el modelo entrenado en un archivo `.sav`
# - El modelo puede ser cargado posteriormente sin necesidad de volver a entrenarlo.
# - Usamos un nombre de archivo descriptivo que refleja los hiperparámetros usados.

dump(model, open("logistic_regression_C-0.1_penalty-l2_solver-liblinear_42.sav", "wb"))

# Ahora el modelo está almacenado y listo para ser reutilizado en futuras predicciones.

# A continuación, podemos proceder a la carga del modelo en otro entorno o notebook.